In [1]:
import pandas as pd
train = pd.read_csv('Train.csv')
test = pd.read_csv('Test.csv')

In [2]:
train.info()
train.head()
train.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23524 entries, 0 to 23523
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   country                 23524 non-null  object
 1   year                    23524 non-null  int64
 2   uniqueid                23524 non-null  object
 3   bank_account            23524 non-null  object
 4   location_type           23524 non-null  object
 5   cellphone_access        23524 non-null  object
 6   household_size          23524 non-null  int64
 7   age_of_respondent       23524 non-null  int64
 8   gender_of_respondent    23524 non-null  object
 9   relationship_with_head  23524 non-null  object
 10  marital_status          23524 non-null  object
 11  education_level         23524 non-null  object
 12  job_type                23524 non-null  object
dtypes: int64(3), object(10)
memory usage: 2.3+ MB

               year  household_size  age_of_respondent
count  23524.000000    23524.000000       23524.000000
mean    2016.975939        3.797483          38.805220
std        0.847371        2.227613          16.520569
min     2016.000000        1.000000          16.000000
25%     2016.000000        2.000000          26.000000
50%     2017.000000        3.000000          35.000000
75%     2018.000000        5.000000          49.000000
max     2018.000000       21.000000         100.000000

Map the target data

In [12]:
# Reload the original train DataFrame to ensure the 'bank_account' column has its original values
train = pd.read_csv('Train.csv')

# Inspect the unique values of 'bank_account' before mapping
print("Unique values in 'bank_account' before mapping:")
print(train['bank_account'].unique())

# Apply the mapping. This line will be adjusted based on the unique values found.
# Assuming 'Yes' and 'No' are the correct values, but if not, this will need modification.
train['bank_account'] = train['bank_account'].map({'Yes':1, 'No':0})

# Display info after mapping
train.info()

Unique values in 'bank_account' before mapping:
['Yes' 'No']
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23524 entries, 0 to 23523
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   country                 23524 non-null  object
 1   year                    23524 non-null  int64
 2   uniqueid                23524 non-null  object
 3   bank_account            23524 non-null  int64
 4   location_type           23524 non-null  object
 5   cellphone_access        23524 non-null  object
 6   household_size          23524 non-null  int64
 7   age_of_respondent       23524 non-null  int64
 8   gender_of_respondent    23524 non-null  object
 9   relationship_with_head  23524 non-null  object
 10  marital_status          23524 non-null  object
 11  education_level         23524 non-null  object
 12  job_type                23524 non-null  object
dtypes: int64(4), object(9)
memory usage: 2.3+ MB

Create age bins

In [4]:
#create the age bins
bins =[0,18,30,50,100]
labels = ['Child','Young Adult','Adult','Senior']
train['age_bins'] = pd.cut(train['age_of_respondent'], bins=bins, labels=labels, right=False)
train.info()
test['age_bins'] = pd.cut(test['age_of_respondent'], bins=bins, labels=labels, right=False)
train.drop('age_of_respondent', axis=1, inplace=True)
test.drop('age_of_respondent', axis=1, inplace=True)
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23524 entries, 0 to 23523
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   country                 23524 non-null  object
 1   year                    23524 non-null  int64
 2   uniqueid                23524 non-null  object
 3   bank_account            23524 non-null  int64
 4   location_type           23524 non-null  object
 5   cellphone_access        23524 non-null  object
 6   household_size          23524 non-null  int64
 7   age_of_respondent       23524 non-null  int64
 8   gender_of_respondent    23524 non-null  object
 9   relationship_with_head  23524 non-null  object
 10  marital_status          23524 non-null  object
 11  education_level         23524 non-null  object
 12  job_type                23524 non-null  object
 13  age_bins                23519 non-null  category
dtypes: category(1), int64(4), object(9)
memory usage: 2.4+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23524 entries, 0 to 23523
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   country                 23524 non-null  object
 1   year                    23524 non-null  int64
 2   uniqueid                23524 non-null  object
 3   bank_account            23524 non-null  int64
 4   location_type           23524 non-null  object
 5   cellphone_access        23524 non-null  object
 6   household_size          23524 non-null  int64
 7   gender_of_respondent    23524 non-null  object
 8   relationship_with_head  23524 non-null  object
 9   marital_status          23524 non-null  object
 10  education_level         23524 non-null  object
 11  job_type                23524 non-null  object
 12  age_bins                23519 non-null  category
dtypes: category(1), int64(3), object(9)
memory usage: 2.2+ MB

Transform education column

In [5]:

train.marital_status.unique()

array(['Married/Living together', 'Widowed', 'Single/Never Married',
       'Divorced/Seperated', 'Dont know'], dtype=object)

In [6]:
family_members = ['Spouse', 'Child', 'Parent', 'Head of Household']
train['is_family'] = train['relationship_with_head'].isin(family_members).astype(int)

test['is_family'] = test['relationship_with_head'].isin(family_members).astype(int)
train.info()
train.drop('relationship_with_head', axis=1, inplace=True)
test.drop('relationship_with_head', axis=1, inplace=True)
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23524 entries, 0 to 23523
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   country                 23524 non-null  object
 1   year                    23524 non-null  int64
 2   uniqueid                23524 non-null  object
 3   bank_account            23524 non-null  int64
 4   location_type           23524 non-null  object
 5   cellphone_access        23524 non-null  object
 6   household_size          23524 non-null  int64
 7   gender_of_respondent    23524 non-null  object
 8   relationship_with_head  23524 non-null  object
 9   marital_status          23524 non-null  object
 10  education_level         23524 non-null  object
 11  job_type                23524 non-null  object
 12  age_bins                23519 non-null  category
 13  is_family               23524 non-null  int64
dtypes: category(1), int64(4), object(9)
memory usage: 2.4+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23524 entries, 0 to 23523
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   country               23524 non-null  object
 1   year                  23524 non-null  int64
 2   uniqueid              23524 non-null  object
 3   bank_account          23524 non-null  int64
 4   location_type         23524 non-null  object
 5   cellphone_access      23524 non-null  object
 6   household_size        23524 non-null  int64
 7   gender_of_respondent  23524 non-null  object
 8   marital_status        23524 non-null  object
 9   education_level       23524 non-null  object
 10  job_type              23524 non-null  object
 11  age_bins              23519 non-null  category
 12  is_family             23524 non-null  int64
dtypes: category(1), int64(4), object(8)
memory usage: 2.2+ MB

In [7]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
train['education_level'] = le.fit_transform(train['education_level'])
test['education_level'] = le.transform(test['education_level'])
train.info()
train.education_level.unique()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23524 entries, 0 to 23523
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   country               23524 non-null  object
 1   year                  23524 non-null  int64
 2   uniqueid              23524 non-null  object
 3   bank_account          23524 non-null  int64
 4   location_type         23524 non-null  object
 5   cellphone_access      23524 non-null  object
 6   household_size        23524 non-null  int64
 7   gender_of_respondent  23524 non-null  object
 8   marital_status        23524 non-null  object
 9   education_level       23524 non-null  int64
 10  job_type              23524 non-null  object
 11  age_bins              23519 non-null  category
 12  is_family             23524 non-null  int64
dtypes: category(1), int64(5), object(7)
memory usage: 2.2+ MB

array([3, 0, 5, 2, 4, 1])

In [8]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23524 entries, 0 to 23523
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   country               23524 non-null  object
 1   year                  23524 non-null  int64
 2   uniqueid              23524 non-null  object
 3   bank_account          23524 non-null  int64
 4   location_type         23524 non-null  object
 5   cellphone_access      23524 non-null  object
 6   household_size        23524 non-null  int64
 7   gender_of_respondent  23524 non-null  object
 8   marital_status        23524 non-null  object
 9   education_level       23524 non-null  int64
 10  job_type              23524 non-null  object
 11  age_bins              23519 non-null  category
 12  is_family             23524 non-null  int64
dtypes: category(1), int64(5), object(7)
memory usage: 2.2+ MB

Marital status

In [9]:
#has a partner
train['has_partner'] = train['marital_status'].isin(['Married/Living together']).astype(int)
test['has_partner'] = test['marital_status'].isin(['Married/Living together']).astype(int)
# 2. Ever Married vs. Never
ever_married_list = ['Married/Living together', 'Widowed', 'Divorced/Seperated']
train['ever_married'] = train['marital_status'].isin(ever_married_list).astype(int)
test['ever_married'] = test['marital_status'].isin(ever_married_list).astype(int)
# 3. Handling 'Dont know' as a specific flag
train['marital_status_unknown'] = (train['marital_status'] == 'Dont know').astype(int)
test['marital_status_unknown'] = (test['marital_status'] == 'Dont know').astype(int)
train.has_partner

0        1
1        0
2        0
3        1
4        0
        ..
23519    0
23520    0
23521    0
23522    0
23523    0
Name: has_partner, Length: 23524, dtype: int64

In [10]:
train.drop('marital_status', axis=1, inplace=True)
test.drop('marital_status', axis=1, inplace=True)

Define X and y

In [13]:
X = train.drop(['uniqueid','bank_account'], axis=1)
y = train['bank_account']
X_final = pd.get_dummies(X, drop_first=True, dtype=int)
X_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23524 entries, 0 to 23523
Data columns (total 32 columns):
 #   Column                                           Non-Null Count  Dtype
---  ------                                           --------------  -----
 0   year                                             23524 non-null  int64
 1   household_size                                   23524 non-null  int64
 2   age_of_respondent                                23524 non-null  int64
 3   country_Rwanda                                   23524 non-null  int64
 4   country_Tanzania                                 23524 non-null  int64
 5   country_Uganda                                   23524 non-null  int64
 6   location_type_Urban                              23524 non-null  int64
 7   cellphone_access_Yes                             23524 non-null  int64
 8   gender_of_respondent_Male                        23524 non-null  int64
 9   relationship_with_head_Head of Household         23524 non-null  int64
 10  relationship_with_head_Other non-relatives       23524 non-null  int64
 11  relationship_with_head_Other relative            23524 non-null  int64
 12  relationship_with_head_Parent                    23524 non-null  int64
 13  relationship_with_head_Spouse                    23524 non-null  int64
 14  marital_status_Dont know                         23524 non-null  int64
 15  marital_status_Married/Living together           23524 non-null  int64
 16  marital_status_Single/Never Married              23524 non-null  int64
 17  marital_status_Widowed                           23524 non-null  int64
 18  education_level_Other/Dont know/RTA              23524 non-null  int64
 19  education_level_Primary education                23524 non-null  int64
 20  education_level_Secondary education              23524 non-null  int64
 21  education_level_Tertiary education               23524 non-null  int64
 22  education_level_Vocational/Specialised training  23524 non-null  int64
 23  job_type_Farming and Fishing                     23524 non-null  int64
 24  job_type_Formally employed Government            23524 non-null  int64
 25  job_type_Formally employed Private               23524 non-null  int64
 26  job_type_Government Dependent                    23524 non-null  int64
 27  job_type_Informally employed                     23524 non-null  int64
 28  job_type_No Income                               23524 non-null  int64
 29  job_type_Other Income                            23524 non-null  int64
 30  job_type_Remittance Dependent                    23524 non-null  int64
 31  job_type_Self employed                           23524 non-null  int64
dtypes: int64(32)
memory usage: 5.7 MB

split and train the train data

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_valid, y_train, y_valid = train_test_split(X_final, y, test_size=0.2,random_state=42)

Model 1. Logistic Regression

In [20]:
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
logic = LogisticRegression(max_iter=1000,random_state=42)
logic.fit(X_train_scaled, y_train)

LogisticRegression(max_iter=1000, random_state=42)

Mean Absolute Error

In [24]:
from sklearn.metrics import mean_absolute_error
X_valid_scaled = scaler.transform(X_valid)
from sklearn.metrics import accuracy_score
y_pred = logic.predict(X_valid_scaled)
# 3. Calculate Accuracy
accuracy = accuracy_score(y_valid, y_pred)
print(f"Accuracy: {accuracy:.4f}")

# 4. Calculate MAE (For your Zindi leaderboard)
mae = 1 - accuracy
print(f"MAE: {mae:.4f}")
# 2. Calculate MAE
mae = mean_absolute_error(y_valid, y_pred)
print(f"Mean Absolute Error: {mae}")

Accuracy: 0.8861
MAE: 0.1139
Mean Absolute Error: 0.11392136025504782

Model 2:Random Forest Classifier

In [31]:
from sklearn import metrics
from sklearn.ensemble import RandomForestClassifier
random = RandomForestClassifier(n_estimators=300, random_state=42)
random.fit(X_train_scaled,y_train)
prediction = random.predict(X_valid_scaled)
print("Accuracy:",metrics.accuracy_score(y_valid, prediction))

Accuracy: 0.8607863974495218

model 3. XGBoost

In [33]:
from xgboost import XGBClassifier
xgb = XGBClassifier(n_estimators=100, max_depth=6, learning_rate=0.1, random_state=42)
xgb.fit(X_train_scaled, y_train)
xgb_pred = xgb.predict(X_valid_scaled)
xgb_accuracy = accuracy_score(y_valid, xgb_pred)
print(f"Accuracy: {xgb_accuracy:.4f}")

Accuracy: 0.8910

Test dataset

In [36]:
#test.info()
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23524 entries, 0 to 23523
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   country                 23524 non-null  object
 1   year                    23524 non-null  int64
 2   uniqueid                23524 non-null  object
 3   bank_account            23524 non-null  int64
 4   location_type           23524 non-null  object
 5   cellphone_access        23524 non-null  object
 6   household_size          23524 non-null  int64
 7   age_of_respondent       23524 non-null  int64
 8   gender_of_respondent    23524 non-null  object
 9   relationship_with_head  23524 non-null  object
 10  marital_status          23524 non-null  object
 11  education_level         23524 non-null  object
 12  job_type                23524 non-null  object
dtypes: int64(4), object(9)
memory usage: 2.3+ MB

In [38]:
# 1. Check if the number of columns matches
print(f"X_train columns: {len(X_train.columns)}")
print(f"test columns:  {len(test.columns)}")

# 2. Check if the names and order are exactly the same
if list(X_train.columns) == list(test.columns):
    print("✅ Columns match perfectly!")
else:
    print("❌ Columns do NOT match!")
    # Show the differences
    missing_in_test = set(X_train.columns) - set(test.columns)
    missing_in_train = set(test.columns) - set(X_train.columns)
    if missing_in_test: print(f"Missing in X_test: {missing_in_test}")
    if missing_in_train: print(f"Missing in X_train: {missing_in_train}")

X_train columns: 32
test columns:  14
❌ Columns do NOT match!
Missing in X_test: {'marital_status_Single/Never Married', 'job_type_Government Dependent', 'marital_status_Widowed', 'job_type_Formally employed Government', 'job_type_Self employed', 'job_type_Formally employed Private', 'relationship_with_head_Other relative', 'marital_status_Married/Living together', 'education_level_Tertiary education', 'relationship_with_head_Other non-relatives', 'gender_of_respondent_Male', 'relationship_with_head_Spouse', 'job_type_Farming and Fishing', 'location_type_Urban', 'marital_status_Dont know', 'relationship_with_head_Parent', 'education_level_Primary education', 'age_of_respondent', 'job_type_No Income', 'job_type_Other Income', 'job_type_Informally employed', 'country_Uganda', 'job_type_Remittance Dependent', 'cellphone_access_Yes', 'education_level_Other/Dont know/RTA', 'education_level_Vocational/Specialised training', 'country_Rwanda', 'education_level_Secondary education', 'relationship_with_head_Head of Household', 'country_Tanzania'}
Missing in X_train: {'uniqueid', 'education_level', 'location_type', 'country', 'job_type', 'is_family', 'ever_married', 'marital_status_unknown', 'age_bins', 'has_partner', 'cellphone_access', 'gender_of_respondent'}

In [40]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder # Assuming 'le' is already fitted from P2_inKC6P182

# 1. Reload the original test DataFrame to ensure all original columns are present
test = pd.read_csv('Test.csv')

# 2. Apply Label Encoding to 'education_level' using the pre-fitted 'le'
# This step was applied to 'train' before X_final was created.
test['education_level'] = le.transform(test['education_level'])

# 3. Create 'age_bins' and drop 'age_of_respondent' as per the 'train' processing
bins =[0,18,30,50,100]
labels = ['Child','Young Adult','Adult','Senior']
test['age_bins'] = pd.cut(test['age_of_respondent'], bins=bins, labels=labels, right=False)
test.drop('age_of_respondent', axis=1, inplace=True)

# 4. Drop 'uniqueid' from test as it's not a feature for the model
test_processed = test.drop('uniqueid', axis=1)

# 5. Apply one-hot encoding to the remaining categorical features to match X_train
# Based on the X_train columns, these columns were one-hot encoded.
cat_cols_for_dummies = ['country', 'location_type', 'cellphone_access', 'gender_of_respondent',
                        'relationship_with_head', 'marital_status', 'job_type']
X_test = pd.get_dummies(test_processed, columns=cat_cols_for_dummies, drop_first=True, dtype=int)

# 6. Reindex X_test to match X_train exactly
X_test = X_test.reindex(columns=X_train.columns, fill_value=0)

# 7. Final Verify
print(f"X_train shape: {X_train.shape}")
print(f"X_test shape:  {X_test.shape}")
print("Match:", list(X_train.columns) == list(X_test.columns))

X_train shape: (18819, 32)
X_test shape:  (10086, 32)
Match: True

In [42]:
X_scaled_test = scaler.transform(X_test)
test_predictions = xgb.predict(X_scaled_test)

make a submission

In [43]:
new_submission = pd.DataFrame({'uniqueid': test['uniqueid'], 'bank_account': test_predictions})
new_submission.to_csv('new_submission.csv', index=False)

In [46]:
print(f"Sample Submission Rows: {len(pd.read_csv('SampleSubmission.csv'))}")
print(f"Your Submission Rows:   {len(new_submission)}")

Sample Submission Rows: 33610
Your Submission Rows:   10086

In [47]:
# 1. Start with the original test IDs (before any drops)
final_df = test[['uniqueid', 'country']].copy()

# 2. Add your predictions (make sure the index matches!)
final_df['bank_account'] = test_predictions

# 3. Create the Zindi ID format
final_df['uniqueid'] = final_df['uniqueid'] + " x " + final_df['country']

# 4. Drop the extra country column
final_df = final_df[['uniqueid', 'bank_account']]

In [48]:
# Convert 1 -> Yes and 0 -> No
final_df['bank_account'] = final_df['bank_account'].map({1: 'Yes', 0: 'No'})

# Final Export
final_df.to_csv('submission_fixed.csv', index=False)